apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
    targetRevision: HEAD
  project: default
  source:
    path: k8s
    repoURL: https://github.com/crogeriorl/k8s-web-color-page.git

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
